# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenMINsapp', '0006_auto_20171125_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under_comments', to='tenMINsapp.Article'),
        ),
    ]
