# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenMINsapp', '0007_comment_belong_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='best_comment',
            field=models.BooleanField(default=False),
        ),
    ]
