# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenMINsapp', '0010_auto_20171128_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
