# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenMINsapp', '0011_auto_20171128_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='cover_image'),
        ),
    ]
