# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenMINsapp', '0014_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editors_choice',
            field=models.BooleanField(default=False),
        ),
    ]
