# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenMINsapp', '0015_article_editors_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
    ]
