# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenMINsapp', '0018_auto_20171201_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_sex',
            field=models.CharField(choices=[('------', '------'), ('男', '男'), ('女', '女')], max_length=10),
        ),
    ]
