# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenMINsapp', '0019_auto_20171202_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_ticket', to='tenMINsapp.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10),
        ),
    ]
